### ISSUE TITLE
[EPIC]: Integrate the compiler-explorer into awesome-os add stealify lang in same turn and cpp2 as also carbon lang

### ISSUE THREAD

**Issue by lemanschik** [stealify/compiler-explorer#1]
### Is your feature request related to a problem? Please describe

# Epic - Stealify Integration
- [ ] It does not run offline it does not run in the browser 
- [ ] it does not use the native filesystem access apis it is not declarativ 
- [ ] it is not ready to get used easy via devtools protocol and other script methods.
- [ ] Its missing a ton of features. 
- [ ] It does not Support Stealify Lang

### Describe the solution you'd like

# Epic - Stealify Integration
Align the existing codebase and add awesome-os wrappers around it as also minify the apis and instructions into the smallest needed denominators to reduce overall code maintenance cost use stealify and integrate stealify to archive the goals.

## Roadmap
- create a minimum set of awesome-os deployments with components for: 
  - i586, 
  - i386, 
  - risc-v 64, 
  - later add more
- Add Service worker fetch on request store into cache
- Add Compiler storage settings eg ondemand (default) or persistent to pin compilers that should stay persistent 
- Load compilers into the awesome-os vm wasm context and execute them as also cache the resulting disk blocks for later export as vfs

### Describe alternatives you've considered

No Alternative Possible this is the Alternative

### Additional context

Context will come up as soon as we do it!
